---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: debug-statements
    - repo: https://github.com/psf/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.8
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11
      hooks:
          - id: yamlfmt
