site_name: PROCESS
docs_dir: "documentation/proc-pages/"
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - I/O: 
        - Input: io/input-guide.md
        - Output: io/output-guide.md
        - Utilities: io/utilities-guide.md
        - Python Libraries: io/python-lib-guide.md
        - Variable Descriptions: vardes.md
    - Solver: solver-guide.md
    - Physics Models:
        - Plasma: physics-models/plasma.md
        - PLASMOD: physics-models/plasmod.md
    - Engineering Models:
        - Machine Build: eng-models/machine-build.md
        - Structural Components: eng-models/structural-components.md
        - Buildings: eng-models/buildings.md
        - First Wall/Blanket: eng-models/fw-blanket.md
        - TF Coil : eng-models/tf-coil.md
        - PF Coil : eng-models/pf-coil.md
        - Central Solenoid : eng-models/central-solenoid.md
        - Shield : eng-models/shield.md
        - Divertor : eng-models/divertor.md
        - Power conversion and heat dissipation systems: eng-models/power-conversion-and-heat-dissipation-systems.md
        - Auxiliary Power Systems: eng-models/auxiliary-power-systems.md
        - Cryostat and vacuum system: eng-models/cryostat-and-vacuum-system.md
    - Misc:
        Spherical Tokamak: misc/spherical-tokamak.md
        Pulsed Plant Operation: misc/pulsed-plant.md
        Stellarator Model: misc/stellarator.md
        Inertial Fusion Energy Model: misc/inertial.md
        Safety and Environment Models: misc/safety.md
        Cost models: misc/cost-models.md
    - Development: 
        Tools: development/tools.md
        Standards: development/standards.md
        Continuous Integration: development/ci-guide.md
        Unit Tests: development/unit-tests.md
    - FORD docs: ford_site/index.html

repo_url: https://git.ccfe.ac.uk/process/process.git

theme: 
    # name: material
    name: readthedocs

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?\
    config=TeX-MML-AM_CHTML"

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde