#   PROCESS f2py run
#   Author    :   K. Zarebski (UKAEA)
#   Date      :   last modified 2020-11-5
#
#   Run f2py on the given files list

MACRO(F2PY)
    EXECUTE_PROCESS (
        COMMAND bash -c "${PYTHON_EXECUTABLE} -c \"import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))\""
        OUTPUT_VARIABLE CMAKE_PYTHON_ABI_VERSION
    )
    STRING(STRIP ${CMAKE_PYTHON_ABI_VERSION} CMAKE_PYTHON_ABI_VERSION)

    SET(F2PY_TARGET ${CMAKE_BINARY_DIR}/_${FORTRAN_INTERFACE_NAME}${CMAKE_PYTHON_ABI_VERSION})
    SET(F2PY_OUTPUT ${PYTHON_MODULE_DIR}/_${FORTRAN_INTERFACE_NAME}${CMAKE_PYTHON_ABI_VERSION})
    SET(F2PY_NAME "f2py")
    MESSAGE(STATUS "[f2py]: ")
    MESSAGE(STATUS "\tTarget: ${F2PY_TARGET}")
    ADD_CUSTOM_TARGET(
        ${F2PY_NAME}
        DEPENDS ${F2PY_TARGET} ${F2PY_OUTPUT}
    )
    ADD_CUSTOM_COMMAND(
        OUTPUT ${F2PY_TARGET} ${F2PY_OUTPUT}
        COMMAND echo "Running f2py to produce target '${F2PY_TARGET}':"
        COMMAND ${F2PY_NAME} -c -m _${FORTRAN_INTERFACE_NAME} -L${PYTHON_LIBS_DIR} -l${PROJECT_NAME} ${F90WRAP_OUTPUT_FILES} --build-dir ${CMAKE_BINARY_DIR}
        COMMAND ${CMAKE_COMMAND} -E copy ${F2PY_TARGET} ${F2PY_OUTPUT}
    )

    ADD_DEPENDENCIES(${F2PY_NAME} ${PIP_NAME} ${F90WRAP_NAME} ${PROJECT_NAME})
ENDMACRO()